<?php
return [
    'disable' => env('CAPTCHA_DISABLE', env('APP_ENV') !== 'production'),
    'characters' => [
        'lowercase' => 'abdefghjklmnpqrstuvwxyz', 
        'uppercase' => 'ABCDEFGHJKLMNPQRSTUVWXYZ', 
        'digits' => '23456789' 
    ],
    'default' => [
        'length' => 5,
        'bgColor' => '#FFFFFF',
        'color' => 'multi',
        'noiseLines' => true,
        'noise' => true,
        'noiseColor' => '#FFFFFF',
        'noiseMode' => 'cross',
        'noiseIntensity' => 1.0,
        'sensitive' => false,
        'digits' => true,
        'uppercase' => true,
        'lowercase' => true,
        'alpha' => 10,
        'blur' => true,
    ],
    'easy' => [
        'length' => 5,
        'bgColor' => '#FFFFFF',
        'color' => 'random',
        'blur' => true,
        'alpha' => 25,
    ],
    'easyDark' => [
        'length' => 5,
        'bgColor' => '#000000',
        'color' => 'random',
        'blur' => true,
        'alpha' => 25,
    ],
    'light' => [
        'bgColor' => '#FFFFFF',
        'color' => '#000000',
        'noise' => true,
        'noiseColor' => '#c5c5c5',
        'noiseMode' => 'vertical',
        'blur' =>true,   
    ],
    'dark' => [
        'bgColor' => '#000000',
        'color' => '#FFFFFF',
        'noise' => true,
        'noiseColor' => '#FFFFFF',
        'noiseMode' => 'vertical',
        'blur' => true
    ],
    'mini' => [
        'length' => 3,
        'bgColor' => '#FFFFFF',
        'color' => 'multi',
        'noise' => true,
        'noiseColor' => 'random',
        'blur' => true,
    ],
    'caps' => [
        'uppercase' => true,
        'lowercase' => false,
        'digits' => false,
        'bgColor' => '#FFFFFF',
        'color' => 'multi',
        'noise' => true,
        'noiseColor' => 'random',
        'noiseMode' => 'random',
        'noiseDensity' => 0.2,
        'noiseIntensity' => 1.0,
        'blur' => true,
        'alpha' => 15
    ],
    'lower' => [
        'uppercase' => false,
        'lowercase' => true,
        'digits' => false,
        'bgColor' => '#FFFFFF',
        'color' => 'multi',
        'noise' => true,
        'noiseColor' => 'random',
        'noiseMode' => 'random',
        'noiseDensity' => 0.2,
        'noiseIntensity' => 1.0,
        'blur' => true,
        'alpha' => 15   
    ],
    'math' => [
        'type' => 'math', 
        'operations' => ['+', '-', '*'], 
        'min_number' => 0,
        'max_number' => 20, 
        'bgColor' => '#FFFFFF',
        'color' => '#000000',
        'noise' => true,
        'noiseColor' => 'random',
        'noiseMode' => 'horizontal',
        'blur' => true,
        'alpha' => 5,
        'fontSize' => 20,
    ]
];